### ISSUE TITLE
add ethernet header pins to teensy4.1 pin PDF

### ISSUE THREAD

**Issue by nmz787** [KurtE/TeensyDocuments#1]
It seems these are missing.

**Comment by silicontraption** [comment]
Agreed, these would be helpful.

The card that comes with the T4.1 is woefully incomplete.

**Comment by KurtE** [comment]
Sorry, I am not really sure what information I would put here that is not on the main T4.1 product page.   Suggestions welcome. 

That is the pins associated with Ethernet are not main processor pins, that we can configure for multiple uses.  

I know that @PaulStoffregen has been working on a new back page for the card.  My guess is that he has already shipped off an updated image to be printed or he will very soon. 

Note: the main product page: https://www.pjrc.com/store/teensy41.html#communication
Now shows an image of the Ethernet connector with labels for each pin. 

Potentially could update showing some of the naming like I did for USB, but already the USB looks sort of messy and I mainly added it to remind myself of orientation (GND up or down?) ...
