### ISSUE TITLE
Redundant CAN pins?

### ISSUE THREAD

**Issue by silicontraption** [KurtE/TeensyDocuments#2]
Are the CAN pins correct? specifically, I'm seeing 3 different pins, all marked TX1, and 3 pins, all marked RX1.

**Comment by KurtE** [comment]
Sorry, I personally have never used CAN so some double checking is probably needed. 

My first pass through shows there may be problems with pins 33 and 34 being marked as CAN.  My look at a previous page for the MUX of pins does not show them as being such. 

I removed those pins being marked as CAN1.  The other two look valid.  TX(11 and 22) and RX(13 and 23)

**Comment by silicontraption** [comment]
Thanks for the update. I'm new to CAN (and T4.1), so I'll double check when I start wiring things up.
