### ISSUE TITLE
teensy pins 0, 1 / micromod 17,19 seems to be swapped

### ISSUE THREAD

**Issue by Digim00n** [KurtE/TeensyDocuments#5]
Teensy4 MicroMod Pins.pdf

**Comment by KurtE** [comment]
Sorry for confusion.   Was fixed in July in the Excel document.   
But I had not generated a PDF file for it with the updates. 

I believe this was fixed with #3 back then

I did a print to generate an updated PDF and uploaded it, plus pasted a picture of it up on the forum
